name: Selenium Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Start Docker Compose
        run: docker-compose -p hubnetwork up --scale chrome=5 --scale firefox=5 --scale edge=5 -d --remove-orphans

#      - name: Run with Maven
#        run: mvn clean test -q

      - name: Run with Docker
        run: |
          docker build -t myimage .
          docker run -t --network=hubnetwork_default --name mycontainer -e DOCKER=true myimage mvn clean test -q
          docker rm mycontainer
          docker rmi myimage -f

      - name: Stop Docker Compose
        run: docker-compose -p hubnetwork down -d --remove-orphans